[package]
name = "whist_browser"
version = "0.1.0"
authors = ["Whist Team"]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/Whist-Team/Whist-Browser"

[profile.dev]
opt-level = 1
debug = 0

[profile.dev.package."*"]
opt-level = 3

[profile.coverage]
inherits = "test"
debug = 2

[profile.release]
opt-level = "z"
debug = 0
lto = true
strip = "debuginfo"
codegen-units = 1

[dependencies]
bevy = { version = "0.7.0", features = ["wayland"] }
bevy_egui = { version = "0.14", default-features = false }
getrandom = { version = "0.2", features = ["js"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
wiremock = "0.5"
tokio = { version = "1", features = ["macros"] }
