[package]
name = "whist_browser"
version = "0.1.0"
authors = ["Whist Team"]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/Whist-Team/Whist-Browser"

[profile.dev]
opt-level = 1
debug = 0

[profile.dev.package."*"]
opt-level = 3

[profile.coverage]
inherits = "test"
debug = 2

[profile.release]
opt-level = "z"
debug = 0
lto = true
strip = "debuginfo"
codegen-units = 1

[dependencies]
bevy_egui = { version = "0.14", default-features = false }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["render", "bevy_winit", "png"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.7"
default-features = false
features = ["x11", "wayland"]

[target.'cfg(target_arch = "wasm32")'.dependencies.getrandom]
version = "0.2"
features = ["js"]

[dev-dependencies]
wiremock = "0.5"
tokio = { version = "1", features = ["macros"] }
