[package]
name = "whist_browser"
version = "0.0.1"
authors = ["Whist Team"]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/Whist-Team/Whist-Browser"

[profile.dev]
opt-level = 1
#debug = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
debug = 0
lto = true
strip = "debuginfo"
codegen-units = 1

[dependencies]
bevy = { version = "0.7.0", features = ["wayland"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
wiremock = "0.5"
tokio = { version = "1", features = ["macros"] }
